[buildPlans.iosevka-rabbits]
family = "Iosevka Rabbits"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.iosevka-rabbits.variants.design]
capital-b = "more-asymmetric-serifless"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "serifless"
capital-j = "descending-flat-hook-serifless"
capital-k = "symmetric-connected-serifless"
capital-m = "slanted-sides-hanging"
capital-n = "standard"
capital-q = "horizontal-tailed"
capital-r = "curly"
capital-s = "serifless"
capital-v = "straight"
capital-w = "straight"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothed"
c = "serifless"
e = "flat-crossbar"
f = "flat-hook-crossbar-at-x-height"
g = "single-storey-earless-corner-flat-hook"
i = "serifless"
j = "flat-hook-serifless"
k = "straight-serifless"
l = "tailed"
m = "normal"
p = "eared"
q = "straight"
t = "cross"
v = "straight"
w = "straight"
x = "straight-serifless"
y = "straight"
z = "straight-serifless"
long-s = "flat-hook-descending"
eszet = "longs-s-lig"
turn-v = "straight"
lower-alpha = "crossing"
lower-delta = "rounded"
lower-iota = "hooky-bottom"
lower-lambda = "straight"
lower-mu = "tailless"
lower-xi = "rounded"
cyrl-capital-zhe = "straight"
cyrl-zhe = "straight"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-el = "straight"
cyrl-capital-u = "curly"
zero = "unslashed-oval"
one = "no-base"
two = "straight-neck"
four = "closed"
five = "oblique-upper-left-bar"
six = "straight-bar"
eight = "two-circles"
nine = "open-contour"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
pilcrow = "low"
caret = "high"
paren = "large-contour"
brace = "curly-flat-boundary"
number-sign = "slanted-tall"
at = "fourfold"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
ascii-single-quote = "straight"
question = "corner-flat-hooked"
punctuation-dot = "round"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.iosevka-rabbits.variants.italic]
capital-a = "curly-tri-serifed"
capital-b = "more-asymmetric-interrupted-bilateral-serifed"
capital-c = "bilateral-inward-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothed-inward-serifed-hooked"
capital-h = "serifed"
capital-i = "serifed"
capital-j = "serifed-both-sides"
capital-k = "symmetric-connected-serifed"
capital-l = "serifed"
capital-m = "flat-bottom-motion-serifed"
capital-n = "motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "crossing"
capital-r = "curly-motion-serifed"
capital-s = "bilateral-serifed"
capital-t = "serifed"
capital-u = "motion-serifed"
capital-v = "curly-motion-serifed"
capital-w = "straight-flat-top-motion-serifed"
capital-x = "curly-serifed"
capital-y = "curly-serifed"
capital-z = "cursive-with-horizontal-crossbar"
a = "double-storey-toothless-rounded"
b = "toothless-rounded"
c = "serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "flat-hook"
g = "earless-corner"
h = "straight"
i = "tailed"
j = "serifless"
k = "cursive-top-left-serifed"
l = "tailed-serifed"
m = "earless-rounded-double-arch"
n = "earless-rounded-straight"
p = "earless-rounded"
q = "earless-rounded"
r = "earless-rounded"
s = "serifless"
t = "standard-short-neck"
u = "toothless-rounded"
w = "cursive"
x = "straight-serifless"
y = "cursive"
z = "straight-serifless"
one = "no-base"
four = "closed-non-crossing"
six = "open-contour"
seven = "straight-serifless"
eight = "crossing-asymmetric"
nine = "open-contour"
asterisk = "turn-hex-low"
at = "fourfold-solid-inner"
dollar = "through-cap"
cent = "through"
percent = "rings-continuous-slash"
ascii-single-quote = "raised-comma"
ascii-grave = "raised-inverse-comma"
question = "smooth"
lig-ltgteq = "slanted"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"

  [buildPlans.iosevka-rabbits.ligations]
  inherits = "dlig"

[buildPlans.iosevka-rabbits.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-rabbits.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-rabbits.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-rabbits.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-rabbits.slopes.italic]
angle = 9.6
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-rabbits.widths.normal]
shape = 475
menu = 5
css = "normal"

# ---- Iosevka QP ------ #
[buildPlans.iosevka-qp]
family = "Iosevka QP"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

[buildPlans.iosevka-qp.variants.design]
capital-b = "more-asymmetric-serifless"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "serifless"
capital-j = "descending-serifless"
capital-k = "symmetric-connected-serifless"
capital-m = "slanted-sides-flat-bottom"
capital-n = "standard"
capital-r = "curly"
capital-s = "serifless"
capital-v = "straight"
capital-w = "straight-flat-top"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothed"
c = "serifless"
e = "flat-crossbar"
f = "flat-hook-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
i = "serifless"
j = "flat-hook-serifless"
k = "straight-serifless"
l = "tailed"
m = "normal"
p = "eared"
q = "straight"
t = "cross"
v = "straight"
w = "straight"
x = "straight-serifless"
y = "straight"
z = "straight-serifless"
long-s = "flat-hook-descending"
eszet = "longs-s-lig"
turn-v = "straight"
lower-alpha = "crossing"
lower-delta = "rounded"
lower-iota = "hooky-bottom"
lower-lambda = "straight"
lower-mu = "tailless"
lower-xi = "rounded"
cyrl-capital-zhe = "straight"
cyrl-zhe = "straight"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-el = "straight"
cyrl-capital-u = "curly"
zero = "unslashed-oval"
one = "no-base"
two = "straight-neck"
four = "closed"
five = "oblique-upper-left-bar"
six = "straight-bar"
eight = "two-circles"
nine = "open-contour"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
pilcrow = "low"
caret = "high"
paren = "large-contour"
brace = "curly-flat-boundary"
number-sign = "slanted-tall"
at = "fourfold"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
ascii-single-quote = "straight"
question = "corner-flat-hooked"
punctuation-dot = "round"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.iosevka-qp.variants.italic]
capital-a = "curly-tri-serifed"
capital-b = "more-asymmetric-interrupted-bilateral-serifed"
capital-c = "bilateral-inward-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothed-inward-serifed-hooked"
capital-h = "serifed"
capital-i = "serifed"
capital-j = "serifed-both-sides"
capital-k = "symmetric-connected-serifed"
capital-l = "serifed"
capital-m = "flat-bottom-motion-serifed"
capital-n = "motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "crossing"
capital-r = "curly-motion-serifed"
capital-s = "bilateral-serifed"
capital-t = "serifed"
capital-u = "motion-serifed"
capital-v = "curly-motion-serifed"
capital-w = "straight-flat-top-motion-serifed"
capital-x = "curly-serifed"
capital-y = "curly-serifed"
capital-z = "cursive-with-horizontal-crossbar"
a = "double-storey-toothless-rounded"
b = "toothless-rounded"
c = "serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "flat-hook"
g = "earless-corner"
h = "straight"
i = "tailed"
j = "serifless"
k = "cursive-top-left-serifed"
l = "tailed-serifed"
m = "earless-rounded-double-arch"
n = "earless-rounded-straight"
p = "earless-rounded"
q = "earless-rounded"
r = "earless-rounded"
s = "serifless"
t = "standard-short-neck"
u = "toothless-rounded"
w = "cursive"
x = "straight-serifless"
y = "cursive"
z = "straight-serifless"
one = "no-base"
four = "closed-non-crossing"
six = "open-contour"
seven = "straight-serifless"
eight = "crossing-asymmetric"
nine = "open-contour"
asterisk = "turn-hex-low"
at = "fourfold-solid-inner"
dollar = "through-cap"
cent = "through"
percent = "rings-continuous-slash"
ascii-single-quote = "raised-comma"
ascii-grave = "raised-inverse-comma"
question = "smooth"
lig-ltgteq = "slanted"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"

[buildPlans.iosevka-qp.ligations]
inherits = "dlig"

[buildPlans.iosevka-qp.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-qp.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-qp.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-qp.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-qp.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-qp.widths.normal]
shape = 475
menu = 5
css = "normal"
